# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = []
CPPPATH = [cwd]

if GetDepend(['RT_HARD_LOCK_USE_DUMMY']):
    src += Glob('drv_hardlock_dummy.c')
else:
    src += Glob('drv_hardlock.c')

group = DefineGroup('HARDLOCK', src, depend = ['RT_USING_HARDLOCK'], CPPPATH = CPPPATH)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
