# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.S')
CPPPATH = [cwd]

if not GetDepend(['RT_USING_SOFT_I2C']):
    SrcRemove(src, 'drv_soft_i2c.c')

group = DefineGroup('I2C', src, depend = ['RT_USING_I2C'], CPPPATH = CPPPATH)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
