# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()
src = Glob('*.c')
CPPPATH = [cwd]

group = DefineGroup('BankVoltageCheck', src, depend = ['RT_USING_PUFS'], CPPPATH = CPPPATH)

Return('group')
