# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = Glob('*.c') + Glob('*.S')
CPPPATH = [cwd]

objs = [DefineGroup('PMU', src, depend = ['RT_USING_RTC_PMU'], CPPPATH = CPPPATH)]

Return('objs')
