# RT-Thread building script for component

from building import *
import os

cwd     = GetCurrentDir()

src     = Glob('*.c')

mpp_dir = os.getenv('MPP_SRC_DIR')

CPPPATH = [
    mpp_dir + '/include',
    mpp_dir + '/include/comm',
    mpp_dir + '/include/ioctl',
]

if os.path.exists(str(mpp_dir) + '/kernel/lib'):
    libdir = mpp_dir + '/kernel/lib'
else:
    libdir = cwd + '/lib'

LIBPATH = [libdir]

libname = ''
liblist = os.listdir(str(libdir))
for item in liblist:
    if item[-2:] == ".a":
        libname = libname + '-l' + item[3:-2] + ' '

LINKFLAGS = ' -Wl,--whole-archive ' + libname  + ' -Wl,--no-whole-archive'
group = DefineGroup('Mpp', src, depend = ['RT_USING_MPP'], CPPPATH = CPPPATH, LINKFLAGS = LINKFLAGS, LIBPATH=LIBPATH)

objs = [group]

list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
