# SPDX-License-Identifier: GPL-2.0

spinand-objs := core.o

spinand-objs += esmt.o
spinand-objs += gigadevice.o
spinand-objs += macronix.o
spinand-objs += micron.o
spinand-objs += paragon.o
spinand-objs += toshiba.o
spinand-objs += winbond.o
spinand-objs += xtx.o

obj-$(CONFIG_MTD_SPI_NAND) += spinand.o
