from building import *

cwd = GetCurrentDir()
CPPPATH = [cwd]

src	= Glob('main.c')
src	+= Glob('mnt.c')
src	+= Glob('config.c')

group = DefineGroup('Applications', src, depend = [''], CPPPATH = CPPPATH)

objs = [group]
list = os.listdir(cwd)

for item in list:
    if os.path.isfile(os.path.join(cwd, item, 'SConscript')):
        objs = objs + SConscript(os.path.join(item, 'SConscript'))

Return('objs')
