# RT-Thread building script for component

from building import *

cwd     = GetCurrentDir()
src     = []

CPPPATH = [cwd]

if GetDepend(['ENABLE_CHERRY_USB_DEVICE']):
    src += Glob('usbd_desc.c')

    if GetDepend(['CHERRY_USB_DEVICE_ENABLE_CLASS_CDC_ACM']):
        src += Glob('usbd_cdc.c')
    if GetDepend(['CHERRY_USB_DEVICE_ENABLE_CLASS_HID']):
        src += Glob('usbd_hid_serial.c')
    if GetDepend(['CHERRY_USB_DEVICE_ENABLE_CLASS_MTP']):
        src += Glob('usbd_mtp.c')
    if GetDepend(['CHERRY_USB_DEVICE_ENABLE_CLASS_UVC']):
        src += Glob('usbd_uvc.c')
    if GetDepend(['CHERRY_USB_DEVICE_ENABLE_CLASS_ADB']):
        src += Glob('usbd_adb.c')

if GetDepend(['ENABLE_CHERRY_USB_HOST']):

    if GetDepend(['CHERRY_USB_HOST_ENABLE_CLASS_NET_RTL8152']):
        src += Glob('usbh_net_rtl8152.c')

    if GetDepend(['CHERRY_USB_HOST_ENABLE_CLASS_CDC_ACM']):
        src += Glob('usbh_cdc_acm.c')

    if GetDepend(['CHERRY_USB_HOST_ENABLE_CLASS_CDC_ECM']):
        src += Glob('usbh_net_ecm.c')

    if GetDepend(['CHERRY_USB_HOST_ENABLE_CLASS_HID']):
        src += Glob('usbh_hid_thr.c')
        src += Glob('rt_input_event.c')
        src += Glob('usbh_hid_report_parser.c')

    if GetDepend(['CHERRY_USB_HOST_ENABLE_CLASS_UVC']):
        src += Glob('usbh_uvc_thr.c')

    if GetDepend(['CHERRY_USB_HOST_ENABLE_CLASS_MSC']):
        src += Glob('usbh_msc_thr.c')

    if GetDepend(['CHERRY_USB_HOST_ENABLE_CLASS_SERIAL_EC200M']):
        src += Glob('usbh_serial_ec200m.c')

    if GetDepend(['CHERRY_USB_HOST_ENABLE_CLASS_CDC_NCM']):
        src += Glob('usbh_net_ncm.c')

group = DefineGroup('CanMVUSB', src, depend = [], CPPPATH = CPPPATH)

objs = [group]

Return('objs')
