#pragma once

#include "usb_cdc.h"

#ifdef CONFIG_ENABLE_DUAL_CDC_PORT
#define CANMV_USB_CDC_ACM_COUNT        2
#else
#define CANMV_USB_CDC_ACM_COUNT        1
#endif

#define CANMV_USB_CDC_INTERFACE_COUNT  (CANMV_USB_CDC_ACM_COUNT * 2)
#define CANMV_USB_CDC_DESCRIPTOR_SIZE  (CDC_ACM_DESCRIPTOR_LEN * CANMV_USB_CDC_ACM_COUNT)
#define CANMV_USB_CDC_NEXT_INTERFACE   CANMV_USB_CDC_INTERFACE_COUNT

#define CANMV_USB_CDC0_CTRL_INTF 0x00
#define CANMV_USB_CDC0_DATA_INTF 0x01

#define CDC_IN_EP   0x81
#define CDC_OUT_EP  0x01
#define CDC_INT_EP  0x82

#ifdef CONFIG_ENABLE_DUAL_CDC_PORT
#define CDC_IN_EP2  0x83
#define CDC_OUT_EP2 0x03
#define CDC_INT_EP2 0x84

#define CANMV_USB_CDC1_CTRL_INTF 0x02
#define CANMV_USB_CDC1_DATA_INTF 0x03

#define CANMV_USB_CDC_SECOND_DESCRIPTOR \
    CDC_ACM_DESCRIPTOR_INIT(CANMV_USB_CDC1_CTRL_INTF, CDC_INT_EP2, CDC_OUT_EP2, CDC_IN_EP2, USB_DEVICE_MAX_MPS, 0x02),
#else
#define CANMV_USB_CDC_SECOND_DESCRIPTOR
#endif
