# RT-Thread building script for component

from building import *
import os

cwd = GetCurrentDir()
src = Glob('*.c')

CPPPATH = [cwd]

group = DefineGroup('FFT', src, depend = ['RT_USING_FFT', 'RT_USING_MPP'], CPPPATH = CPPPATH)

objs = [group]

Return('objs')