
obj-$(CONFIG_$(SPL_)KBURN) += kburn.o

obj-$(CONFIG_$(SPL_)KBURN_MMC) += kburn_mmc.o
obj-$(CONFIG_$(SPL_)KBURN_SF) += kburn_sf.o
obj-$(CONFIG_$(SPL_)KBURN_MTD) += kburn_mtd.o
obj-$(CONFIG_$(SPL_)KBURN_OTP) += kburn_otp.o
