# RT-Thread building script for component

from building import *

cwd = GetCurrentDir()

path = [cwd]
path += [cwd + '/api']
path += [cwd + '/include']
path += [cwd + '/os/customer_rtos']
path += [cwd + '/os/os_dep/include']
path += [cwd + '/platform/include']
path += [cwd + '/platform/rtwlan_bsp']
path += [cwd + '/platform/sdio']
path += [cwd + '/platform/sdio/include']

src = Glob('*.c')
src += Glob('api/*.c')
src += Glob('api/wifi/*.c')
src += Glob('os/customer_rtos/customer_rtt_service.c')
src += Glob('os/os_dep/*.c')
src += Glob('platform/rtwlan_bsp/*.c')
src += Glob('platform/sdio/*.c')

libs=[]
libpath=[]
lib_base_path=[]

if GetDepend('REALTEK_SDIO_RTL8733BS'):
    libs += ['wlan_rtl8733BS_v1_2']
    lib_base_path = cwd + '/wlan_lib/8733/'
elif GetDepend('REALTEK_SDIO_RTL8189FTV'):
    libs += ['wlan_rtl8189FTV_v1_1']
    lib_base_path = cwd + '/wlan_lib/8189/'

path += [lib_base_path]
libpath += [lib_base_path]

group = DefineGroup('realtek', src, depend = ['RT_USING_REALTEK'], CPPPATH = path, LIBS = libs, LIBPATH = libpath)

Return('group')
